name: sqlite_demo
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # retrofit.dart is an dio client generator using source_gen and inspired by Chopper and Retrofit.
  retrofit: ^1.3.4

  # Automatically generate code for converting to and from JSON by annotating Dart classes.
  json_serializable: ^3.4.1

  # Classes and helper functions that support JSON code generation via the `json_serializable` package.
  json_annotation: ^3.0.1

  # Open screens/snackbars/dialogs without context, manage states and inject dependencies easily with GetX.
  get: ^3.6.2

  # Simple direct Service Locator that allows to decouple the interface from a concrete implementation and to access the concrete implementation from everywhere in your App"
  get_it: ^5.0.0

  # Injectable is a convenient code generator for get_it. Inspired by Angular DI, Guice DI and inject.dart.
  injectable: ^1.0.5

  # Suga Core Package.
  suga_core: ^0.3.1

  # Flutter plugin for SQLite, a self-contained, high-reliability, embedded, SQL database engine.
  sqflite: ^1.3.2+4

  # A library to enable sqlite db migrations, using sqflite plugin.
  sqflite_migration: ^0.2.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

  # Easy and Fast internationalizing and localization your Flutter Apps, this package simplify the internationalizing process .
  easy_localization: ^2.3.3

  image_picker: ^0.6.7+22

  # A mock framework inspired by Mockito.
  mockito: ^4.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  # A build system for Dart code generation and modular compilation.
  build_runner: ^1.10.1

  # Injectable is a convenient code generator for get_it. Inspired by Angular DI, Guice DI and inject.dart.
  injectable_generator: ^1.0.4

  # retrofit generator is an dio client generator using source_gen and inspired by Chopper and Retrofit.
  retrofit_generator: ^1.3.7+6

  # The Flutter code generator for your assets, fonts, colors, … — Get rid of all String-based APIs.
  flutter_gen: ^1.2.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - resources/

